// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCopa2026.Data;

#nullable disable

namespace PortalCopa2026.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910022642_AddFaseEliminatoria")]
    partial class AddFaseEliminatoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gols")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipacoesCopa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JogoOrigemMandanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JogoOrigemVisitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlacarMandante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlacarPenaltisMandante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlacarPenaltisVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlacarVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelecaoMandanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelecaoVisitanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("JogoOrigemMandanteId");

                    b.HasIndex("JogoOrigemVisitanteId");

                    b.HasIndex("SelecaoMandanteId");

                    b.HasIndex("SelecaoVisitanteId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.RankingFifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Pontos")
                        .HasColumnType("REAL");

                    b.Property<int>("Posicao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId")
                        .IsUnique();

                    b.ToTable("RankingsFifa");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Selecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tecnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("GrupoId");

                    b.ToTable("Selecoes");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Simulacao.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Simulacao.SimulacaoJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlacarMandante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlacarVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimulacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("SimulacaoId");

                    b.ToTable("SimulacaoJogos");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Jogador", b =>
                {
                    b.HasOne("PortalCopa2026.Models.Copa.Selecao", "Selecao")
                        .WithMany("Jogadores")
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selecao");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Jogo", b =>
                {
                    b.HasOne("PortalCopa2026.Models.Copa.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalCopa2026.Models.Copa.Jogo", "JogoOrigemMandante")
                        .WithMany()
                        .HasForeignKey("JogoOrigemMandanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalCopa2026.Models.Copa.Jogo", "JogoOrigemVisitante")
                        .WithMany()
                        .HasForeignKey("JogoOrigemVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalCopa2026.Models.Copa.Selecao", "SelecaoMandante")
                        .WithMany()
                        .HasForeignKey("SelecaoMandanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalCopa2026.Models.Copa.Selecao", "SelecaoVisitante")
                        .WithMany()
                        .HasForeignKey("SelecaoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grupo");

                    b.Navigation("JogoOrigemMandante");

                    b.Navigation("JogoOrigemVisitante");

                    b.Navigation("SelecaoMandante");

                    b.Navigation("SelecaoVisitante");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.RankingFifa", b =>
                {
                    b.HasOne("PortalCopa2026.Models.Copa.Selecao", "Selecao")
                        .WithOne("RankingFifa")
                        .HasForeignKey("PortalCopa2026.Models.Copa.RankingFifa", "SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selecao");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Selecao", b =>
                {
                    b.HasOne("PortalCopa2026.Models.Copa.Grupo", "Grupo")
                        .WithMany("Selecoes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Simulacao.SimulacaoJogo", b =>
                {
                    b.HasOne("PortalCopa2026.Models.Copa.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalCopa2026.Models.Simulacao.Simulacao", "Simulacao")
                        .WithMany("Jogos")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Grupo", b =>
                {
                    b.Navigation("Selecoes");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Copa.Selecao", b =>
                {
                    b.Navigation("Jogadores");

                    b.Navigation("RankingFifa");
                });

            modelBuilder.Entity("PortalCopa2026.Models.Simulacao.Simulacao", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
